[log]
    relative    = true          # true: Default use relative path, false: use absolute path.
    debug       = true          # Enable console debugger.
    dir         =  "logs"       # Log storage directory.
    name        = "app.log"     # Log filename.
    prefix      =  ""           # Prefix for cutting log filename.
    level       =  "INFO"       # The log level, if the value is OFF, then log off.
